TRUNCATE TABLE PUBLIC.PE_COMUNICACAO_CATEGORIA_CONTEUDO;

TRUNCATE TABLE PUBLIC.PE_COMUNICACAO_CONTEUDO;

TRUNCATE TABLE PUBLIC.PE_COMUNICACAO_BANNER;


INSERT INTO "PUBLIC"."PE_COMUNICACAO_CATEGORIA_CONTEUDO"
( ID, ATIVO, TITULO )
VALUES ( 1, true, 'Qualidade');

INSERT INTO "PUBLIC"."PE_COMUNICACAO_CATEGORIA_CONTEUDO"
( ID, ATIVO, TITULO )
VALUES ( 2, true, 'Processos');

INSERT INTO "PUBLIC"."PE_COMUNICACAO_CATEGORIA_CONTEUDO"
( ID, ATIVO, TITULO )
VALUES ( 3, true, 'Comunicação');

INSERT INTO "PUBLIC"."PE_COMUNICACAO_CATEGORIA_CONTEUDO"
( ID, ATIVO, TITULO )
VALUES ( 4, true, 'Problemas Sistêmicos');

INSERT INTO "PUBLIC"."PE_COMUNICACAO_CONTEUDO"
( "ID", "ATIVO", "TITULO", "DATACRIACAO", "TEXTO", "CATEGORIA_ID", "IMAGEM_ID" )
VALUES ( 1, true, 'Teste', CURRENT_TIMESTAMP, 'Teste Teste Teste', 1, null);

INSERT INTO "PUBLIC"."PE_COMUNICACAO_BANNER"
( "ID", "ATIVO", "TITULO", "DATAFIM", "DATAINICIO", "DATACRIACAO", "LOCAL", "CONTEUDO_ID" )
VALUES ( 1, true, 'Teste', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, null );