INSERT INTO "PUBLIC"."PUBLIC".PE_ABA (ATIVO, TITULO)
	VALUES (true, 'lkjhlkjh');

INSERT INTO "PUBLIC"."PUBLIC".PE_SUBABA (ATIVO, TITULO, ABAPORTAL_ID)
	VALUES (true, 'Teste', 1);

INSERT INTO "PUBLIC"."PUBLIC".PE_SUBABA (ATIVO, TITULO, ABAPORTAL_ID)
	VALUES (true, 'Teste', 1);


INSERT INTO "PUBLIC"."PUBLIC".PE_ENQUETE (ATIVO, TITULO, DATAFIM, DATAINICIO)
	VALUES (true, 'Titulo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


SELECT * FROM "PUBLIC".PE_ENQUETE LIMIT 4000;

SELECT * FROM "PUBLIC".PE_SUBABA LIMIT 4000;

SELECT * FROM "PUBLIC".PE_ABA LIMIT 4000;
