INSERT INTO "PUBLIC"."PUBLIC".PE_ENQUETE (ATIVO, TITULO, DATAFIM, DATAINICIO)
	VALUES (true, 'Titulo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO "PUBLIC"."PUBLIC".PE_PERGUNTA_ENQUETE (ATIVO, TITULO, ENQUETE_ID, TIPOPERGUNTA)
	VALUES (true, 'Pergunta 1?', 1, 'pergunta');