TRUNCATE TABLE PUBLIC.PE_ESCOLHA_PERGUNTA_ENQUETE;
TRUNCATE TABLE PUBLIC.PE_PERGUNTA_ENQUETE;
TRUNCATE TABLE PUBLIC.PE_ENQUETE;

INSERT INTO "PUBLIC".PE_ENQUETE (ID, ATIVO, TITULO, DATAFIM, DATAINICIO)
    VALUES (1, true, 'Titulo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO "PUBLIC".PE_PERGUNTA_ENQUETE (ID, ATIVO, TITULO, ENQUETE_ID, TIPOPERGUNTA)
    VALUES (1, true, 'Pergunta 1?', 1, 'pergunta');

INSERT INTO "PUBLIC".PE_PERGUNTA_ENQUETE (ID, ATIVO, TITULO, ENQUETE_ID, TIPOPERGUNTA)
    VALUES (2, true, 'Pergunta 2?', 1, 'Múltipla Escolha');

INSERT INTO "PUBLIC"."PE_ESCOLHA_PERGUNTA_ENQUETE" (ID, ATIVO, TITULO, PERGUNTA_ID ) 
    VALUES (1, true, 'Escolha 1', 2);